defmodule AdventOfCode.Day08Test do
  use ExUnit.Case

  import AdventOfCode.Day08

  @input """
         ............
         ........0...
         .....0......
         .......0....
         ....0.......
         ......A.....
         ............
         ............
         ........A...
         .........A..
         ............
         ............
         """
         |> AdventOfCode.Input.Day08.parse()

  test "part1", do: assert(part1(@input) == 14)
  test "part2", do: assert(part2(@input) == 34)
end
